#!/system/bin/sh
echo "=== CTS PROPERTY CHECK ==="
echo "flash.locked=$(/system/bin/getprop ro.boot.flash.locked)"
echo "vbmeta.device_state=$(/system/bin/getprop ro.boot.vbmeta.device_state)"
echo "verifiedbootstate=$(/system/bin/getprop ro.boot.verifiedbootstate)"
echo "build.type=$(/system/bin/getprop ro.build.type)"
echo "build.tags=$(/system/bin/getprop ro.build.tags)"
echo "security_patch=$(/system/bin/getprop ro.build.version.security_patch)"
echo "first_api_level=$(/system/bin/getprop ro.product.first_api_level)"
echo "oem_unlock=$(/system/bin/getprop ro.oem_unlock_supported)"
echo "selinux=$(getenforce 2>/dev/null)"
echo "ro.debuggable=$(/system/bin/getprop ro.debuggable)"
echo "ro.secure=$(/system/bin/getprop ro.secure)"
echo "ro.adb.secure=$(/system/bin/getprop ro.adb.secure)"
echo "=== END ==="
